### ISSUE TITLE
For a new readline.Editor, the input is from os.StdIn, does it support the user-specified io stream as the command input source

### ISSUE THREAD

**Issue by 81981266** [nyaosorg/go-readline-ny#7]
For a new readline.Editor, the input is from os.StdIn, does it support the user-specified io stream as the command input source

**Comment by hymkor** [comment]
Yes, it is supported.

```go
type Editor struct {
// 
	Tty            ITty
//
}
```

Users can set the field `Tty` the handler to get keys from stream.

```go
type ITty interface {
	Open(onSize func(int)) error // onSize is the function to call with screen-width when screen size is changed.
	GetKey() (string, error) // the returned value is defined on https://github.com/nyaosorg/go-readline-ny/blob/master/keys/code.go
	Size() (int, int, error) // the returned value is the width and height of the screen.
	Close() error
}
```

Sample code:

- https://github.com/nyaosorg/go-readline-ny/blob/master/auto/main.go
- https://github.com/nyaosorg/go-readline-ny/blob/master/auto/main_test.go

**Comment by hymkor** [comment]
I will close this issue. But, if any questions, would you re-open and write them.
